name: 'Save Cache'
description: 'Archive and upload cache to GitHub Releases'
inputs:
  cache_path:
    description: 'Path where cache is saved'
    required: true
    type: string
  cache_key:
    description: 'Unique key for the cache'
    required: true
    type: string
  cache_bucket:
    description: 'The tag name for the release (e.g., general-cache)'
    required: true
    default: 'general-cache'
  github_token:
    description: 'GitHub Token'
    required: true
  compression_level:
    description: 'Compression level (0-9). 0 = No compression, 1 = Fast, 19 = Best.'
    required: false
    type: number
    default: 6
  working_dir:
    description: 'Path where .git folder exists (use only if you clone multiple repos)'
    required: false
    type: string
  debug:
    description: 'Enable Logs'
    required: false
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
    - name: Archive Cache
      uses: ./.github/actions/cache-archive
      with:
        cache_path: ${{ inputs.cache_path }}
        cache_key: ${{ inputs.cache_key }}
        cache_bucket: ${{ inputs.cache_bucket }}
        compression_level: ${{ inputs.compression_level }}
        working_dir: ${{ inputs.working_dir }}
        debug: ${{ inputs.debug }}

    - name: Upload Cache
      uses: ./.github/actions/cache-upload
      with:
        cache_key: ${{ inputs.cache_key }}
        cache_bucket: ${{ inputs.cache_bucket }}
        github_token: ${{ inputs.github_token }}
        compression_level: ${{ inputs.compression_level }}
        debug: ${{ inputs.debug }}
